#!/bin/bash

set -e

dir=$(dirname $0)

cd $dir

# Generate documentation and commit it to the gh-pages branch
doxygen docs/config.dox

git checkout gh-pages

cp -r docs/html/* docs/

git add docs/
git commit
git push

git checkout master
